apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secrets
  namespace: targeting-service
type: Opaque
stringData:
  POSTGRES_USER: "postgres"  
  POSTGRES_PASSWORD: "postgres"
  MASTER_KEY: "admin-secreto-123"
  DATABASE_URL: "postgres://postgres:postgres@postgres-targeting-db.cyvo4suykdq6.us-east-1.rds.amazonaws.com:5432/targeting_db"